# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: hello_rails
  username: Rails.application.credentials.dig(:postgres, :username, :development)
  password: Rails.application.credentials.dig(:postgres, :password, :development)

test:
  <<: *default
  database: hello_rails_test
  username: Rails.application.credentials.dig(:postgres, :username, :testing)
  password: Rails.application.credentials.dig(:postgres, :password, :testing)

production:
  <<: *default
  database: hello_rails
  username: Rails.application.credentials.dig(:postgres, :username, :production)
  password: Rails.application.credentials.dig(:postgres, :password, :production)
